### ISSUE TITLE
No attribute 'get'

### ISSUE THREAD

**Issue by HarvsG** [HarvsG/ha-glinet4-integration#1]
https://github.com/HarvsG/ha-glinet4-integration/blob/8abeb58b24248019d054278a132766f02be59819/router.py#L280

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant
Source: custom_components/glinet/router.py:280
Integration: GL-inet
First occurred: July 25, 2023 at 1:02:20 AM (7783 occurrences)
Last logged: 5:53:20 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/glinet/router.py", line 200, in update_all
    await self.update_device_trackers()
  File "/config/custom_components/glinet/router.py", line 280, in update_device_trackers
    dev_info = wrt_devices.get(device_mac)
               ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by HarvsG** [comment]
Should be fixed
