### ISSUE TITLE
config flow unsuccessfull when trying to add GL-XE300 router

### ISSUE THREAD

**Issue by jurviz** [HarvsG/ha-glinet4-integration#12]
I tried to install your custom integration into my test environment and i'm getting an error when i try to configure the integration. 
See messages from the log. I tried several times by deleting the integration and adding it again, installint the tailscale pulgins (that i don't use). 
My router is a GL-XE300 (Puli) with the latest V4 firmware installed.
Home Assistant is also the latest version (2024.8.1)
```
2024-08-13T16:57:02.076430262Z [33m2024-08-13 18:57:02.072 WARNING (MainThread) [custom_components.glinet.config_flow] Attempting to connect to router, success:True[0m
2024-08-13T16:57:02.403075602Z Exception ignored in: <function AiohttpClient.__del__ at 0xffff75aa19e0>
2024-08-13T16:57:02.403178277Z Traceback (most recent call last):
2024-08-13T16:57:02.403199571Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/aiohttp_.py", line 75, in __del__
2024-08-13T16:57:02.404728609Z     asyncio.get_event_loop().run_until_complete(
2024-08-13T16:57:02.404830992Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 663, in run_until_complete
2024-08-13T16:57:02.405272027Z     self._check_running()
2024-08-13T16:57:02.406579089Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 622, in _check_running
2024-08-13T16:57:02.406667471Z     raise RuntimeError('This event loop is already running')
2024-08-13T16:57:02.406994455Z RuntimeError: This event loop is already running
2024-08-13T16:57:02.414075809Z [33m2024-08-13 18:57:02.409 WARNING (Thread-51 (_target)) [py.warnings] /usr/local/lib/python3.12/asyncio/base_events.py:2008: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
2024-08-13T16:57:02.414201527Z   def get_debug(self):
2024-08-13T16:57:02.414229238Z [0m
2024-08-13T16:57:02.415056762Z [31m2024-08-13 18:57:02.410 ERROR (Thread-51 (_target)) [homeassistant] Error doing job: Unclosed client session (None)[0m
2024-08-13T16:57:02.415875827Z [31m2024-08-13 18:57:02.411 ERROR (Thread-51 (_target)) [homeassistant] Error doing job: Unclosed connector (None)[0m
2024-08-13T16:57:03.055270988Z [31m2024-08-13 18:57:03.047 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry GL-inet Xe300 for glinet
2024-08-13T16:57:03.055398457Z Traceback (most recent call last):
2024-08-13T16:57:03.055425876Z   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
2024-08-13T16:57:03.055445710Z     result = await component.async_setup_entry(hass, self)
2024-08-13T16:57:03.055463795Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.055481297Z   File "/config/custom_components/glinet/__init__.py", line 53, in async_setup_entry
2024-08-13T16:57:03.055499090Z     await router.setup()
2024-08-13T16:57:03.055517466Z   File "/config/custom_components/glinet/router.py", line 154, in setup
2024-08-13T16:57:03.055534676Z     await self.update_all()
2024-08-13T16:57:03.055551886Z   File "/config/custom_components/glinet/router.py", line 207, in update_all
2024-08-13T16:57:03.055569095Z     await self.update_tailscale_state()
2024-08-13T16:57:03.055586597Z   File "/config/custom_components/glinet/router.py", line 330, in update_tailscale_state
2024-08-13T16:57:03.055604098Z     if not await self._api.tailscale_configured():
2024-08-13T16:57:03.055670603Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.055695397Z   File "/usr/local/lib/python3.12/site-packages/gli4py/glinet.py", line 238, in tailscale_configured
2024-08-13T16:57:03.055779404Z     if await self._tailscale_status() != []:
2024-08-13T16:57:03.055799530Z        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.055817615Z   File "/usr/local/lib/python3.12/site-packages/gli4py/glinet.py", line 229, in _tailscale_status
2024-08-13T16:57:03.055835700Z     return await self._request(self.gen_sid_payload('call', ['tailscale', 'get_status'], self.sid))
2024-08-13T16:57:03.055853201Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.055871286Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/io/asyncio_strategy.py", line 32, in execute
2024-08-13T16:57:03.055888787Z     return await executable.execute()
2024-08-13T16:57:03.055905997Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.055923790Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/io/asyncio_strategy.py", line 21, in invoke
2024-08-13T16:57:03.055941583Z     response = await callback.on_success(response)
2024-08-13T16:57:03.055958501Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.055976003Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/io/asyncio_strategy.py", line 19, in invoke
2024-08-13T16:57:03.055993796Z     response = await callback.on_failure(type(error), error, tb)
2024-08-13T16:57:03.056011005Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.056036091Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/io/execution.py", line 108, in on_failure
2024-08-13T16:57:03.056054759Z     return self._io.fail(exc_type, exc_val, exc_tb)
2024-08-13T16:57:03.056072844Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.056090637Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/io/interfaces.py", line 300, in fail
2024-08-13T16:57:03.056107846Z     compat.reraise(exc_type, exc_val, exc_tb)
2024-08-13T16:57:03.056125056Z   File "/usr/local/lib/python3.12/site-packages/six.py", line 719, in reraise
2024-08-13T16:57:03.056142849Z     raise value
2024-08-13T16:57:03.056167934Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/io/asyncio_strategy.py", line 16, in invoke
2024-08-13T16:57:03.056186311Z     response = await func(*args, **kwargs)
2024-08-13T16:57:03.056202937Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.056220439Z   File "/usr/local/lib/python3.12/site-packages/uplink/clients/aiohttp_.py", line 27, in new_callback
2024-08-13T16:57:03.056238232Z     response = callback(response)
2024-08-13T16:57:03.056255150Z                ^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.056272651Z   File "/usr/local/lib/python3.12/site-packages/uplink/builder.py", line 47, in wrapper
2024-08-13T16:57:03.056290444Z     return func(self._consumer, *args, **kwargs)
2024-08-13T16:57:03.056354616Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.056373867Z   File "/usr/local/lib/python3.12/site-packages/uplink/hooks.py", line 21, in wrapper
2024-08-13T16:57:03.056391661Z     return hook(*args, **kwargs)
2024-08-13T16:57:03.056408870Z            ^^^^^^^^^^^^^^^^^^^^^
2024-08-13T16:57:03.056426080Z   File "/usr/local/lib/python3.12/site-packages/gli4py/error_handling.py", line 33, in raise_for_status
2024-08-13T16:57:03.056444165Z     raise NonZeroResponse("Request returned error code %s with message:' %s'. Full response %s" % (res['error']['code'], res['error']['message'],res))
2024-08-13T16:57:03.056462833Z gli4py.error_handling.NonZeroResponse: Request returned error code -32601 with message:' Method not found'. Full response {'id': 0, 'jsonrpc': '2.0', 'error': {'message': 'Method not found', 'code': -32601}}[0m

```

**Comment by HarvsG** [comment]
Hmm method not found sounds as if Gl-inet may have some variation in the API.
Out of interest, does your device support tailscale? It looks as if that is the request that is erroring.

**Comment by HarvsG** [comment]
Try updating and see where it gets you.

**Comment by jurviz** [comment]
After updating and restarting Home Assistant the integration has found one device.

**Comment by HarvsG** [comment]
Brilliant, thanks for the feedback @jurviz 
Let me know if you have any other issues
