### ISSUE TITLE
Error setting up entry GL-inet X3000 for glinet

### ISSUE THREAD

**Issue by mllockwood** [HarvsG/ha-glinet4-integration#13]
I have setup the X3000 device, but it will not actually connect and this is the error I receive:

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 7:20:23 PM (4 occurrences)
Last logged: 7:42:03 PM

Error setting up entry GL-inet X3000 for glinet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/__init__.py", line 53, in async_setup_entry
    await router.setup()
  File "/config/custom_components/glinet/router.py", line 131, in setup
    entity_registry = er_helper.async_get(self.hass)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given

**Comment by HarvsG** [comment]
Still having the issue?
Can you share more info on the version of the router and homeassistant that you are using?
