### ISSUE TITLE
Cannot Setup Router GL-inet Ax1800

### ISSUE THREAD

**Issue by chinswain** [HarvsG/ha-glinet4-integration#6]
After connecting to my router I get  a sucess message ( Created configuration for GL-inet Ax1800. ).
However the integration instantly states "Failed to set up". Firmware is v4.1.0

```


2023-09-24 00:43:48.635 ERROR (MainThread) [custom_components.glinet.router] Response from http://192.168.86.1 to request wireguard_client_list is of type <class 'list'>, Response: []
2023-09-24 00:43:48.662 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry GL-inet Ax1800 for glinet
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/glinet/__init__.py", line 53, in async_setup_entry
await router.setup()
File "/config/custom_components/glinet/router.py", line 148, in setup
await self.update_all()
File "/config/custom_components/glinet/router.py", line 200, in update_all
await self.update_wireguard_client_state()
File "/config/custom_components/glinet/router.py", line 322, in update_wireguard_client_state
self._wireguard_clients[response["peer_id"]].connected = (response["status"] == 1)
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 0

```

**Comment by HarvsG** [comment]
Try reloading the integration in the ui (Settings -> devices and services -> GL-inet -> Three dot menu -> reload)

I currently have to do that after every restart, I'm not sure why.

**Comment by HarvsG** [comment]
Any progress?

**Comment by alexandrepossebom** [comment]
Same problem here with GL-inet Mt6000.

**Comment by alexandrepossebom** [comment]
> Try reloading the integration in the ui (Settings -> devices and services -> GL-inet -> Three dot menu -> reload)
> 
> I currently have to do that after every restart, I'm not sure why.

I did it and not worked.

**Comment by chinswain** [comment]
Same for me still

**Comment by rogerdempsey** [comment]
same problem with  GL-SFT1200

**Comment by HarvsG** [comment]
Try again now, hopefully fixed in a recent version

**Comment by HarvsG** [comment]
Anything to report @rogerdempsey @chinswain @alexandrepossebom ?

**Comment by firewalkwithm3** [comment]
> Try again now, hopefully fixed in a recent version

I was also having this issue with my GL-AX1800 but can confirm the latest version has fixed it.

**Comment by chinswain** [comment]
Confirmed working.
