### ISSUE TITLE
Problem with GL.iNet Flint (GL-AX1800) Integration Setup: Unexpected Error

### ISSUE THREAD

**Issue by galaxyrun** [HarvsG/ha-glinet4-integration#8]
I just wanted to set up the integration, but unfortunately I have the following error with my gl.inet Flint (GL-AX1800):

<img width="395" alt="image" src="https://github.com/HarvsG/ha-glinet4-integration/assets/76906352/81d9c95f-703a-431a-b95e-e0442ee8488b">

```
Logger: custom_components.glinet.config_flow
Source: custom_components/glinet/config_flow.py:128
Integration: glinet
First occurred: 08:27:03 (3 occurrences)
Last logged: 08:27:09

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/glinet/config_flow.py", line 128, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/config_flow.py", line 90, in validate_input
    if not await hub.connect():
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/config_flow.py", line 49, in connect
    res = await self.router.router_model()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 32, in execute
    return await executable.execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 21, in invoke
    response = await callback.on_success(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 19, in invoke
    response = await callback.on_failure(type(error), error, tb)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/execution.py", line 108, in on_failure
    return self._io.fail(exc_type, exc_val, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/interfaces.py", line 300, in fail
    compat.reraise(exc_type, exc_val, exc_tb)
  File "/usr/local/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 16, in invoke
    response = await func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/aiohttp_.py", line 27, in new_callback
    response = callback(response)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/builder.py", line 47, in wrapper
    return func(self._consumer, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/hooks.py", line 21, in wrapper
    return hook(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gli_py/error_handling.py", line 34, in raise_for_status
    raise UnsuccessfulRequest(response.url)
gli_py.error_handling.UnsuccessfulRequest: http://192.168.8.1/cgi-bin/api/router/model

```

Any idea how I can solve this?

**Comment by HarvsG** [comment]
are you sure your router is at http://192.168.8.1 and is running version 4 software?

**Comment by HarvsG** [comment]
Thats the OpenWRT version
what about when you go to:
http://192.168.8.1/#/upgrade
