### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by leon0399** [HarvsG/ha-glinet4-integration#9]
Unfortunately, seems like something got broken, I cannot add integration, this is what I get:
![image](https://github.com/HarvsG/ha-glinet4-integration/assets/1759654/7f6bfcef-7976-4e08-81b8-cae1aab7391c)

And here are system logs:
```
2023-12-15 12:32:23.786 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.glinet.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 834, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 851, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1204, in _gcd_import
  File "", line 1176, in _find_and_load
  File "", line 1126, in _find_and_load_unlocked
  File "", line 241, in _call_with_frames_removed
  File "", line 1204, in _gcd_import
  File "", line 1176, in _find_and_load
  File "", line 1147, in _find_and_load_unlocked
  File "", line 690, in _load_unlocked
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/config/custom_components/glinet/__init__.py", line 9, in 
    from .router import GLinetRouter
  File "/config/custom_components/glinet/router.py", line 322
    if self._wireguard_clients[response["peer_id"]]
                                                   ^
SyntaxError: expected ':'
```

**Comment by HarvsG** [comment]
I introduced a bug, made a change, you will need to re download (or just replace router.py), try now?

**Comment by mihsu81** [comment]
After applying the fix, we can add the devices but the integration fails to set up and a couple of errors appear in the logs.

```
This error originated from a custom integration.

Logger: custom_components.glinet.router
Source: custom_components/glinet/router.py:251
Integration: GL-inet
First occurred: 18:56:57 (1 occurrences)
Last logged: 18:56:57

Response from http://192.168.45.246 to request wireguard_client_list is of type <class 'list'>, Response: []
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 18:56:57 (1 occurrences)
Last logged: 18:56:57

Error setting up entry GL-inet Mt300n-v2 for glinet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/__init__.py", line 53, in async_setup_entry
    await router.setup()
  File "/config/custom_components/glinet/router.py", line 148, in setup
    await self.update_all()
  File "/config/custom_components/glinet/router.py", line 200, in update_all
    await self.update_wireguard_client_state()
  File "/config/custom_components/glinet/router.py", line 322, in update_wireguard_client_state
    if self._wireguard_clients[response["peer_id"]]:
       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 0
```

![image](https://github.com/HarvsG/ha-glinet4-integration/assets/40715497/f3be3113-0fb1-4a74-8062-ff935bebf675)

**Comment by leon0399** [comment]
Thanx for a fix @HarvsG! Now I've been able to set up integration, but unfortunately it still does not work correctly :(
Only the WireGuard VPN switch appeared, and it would've been enough for me, but it does not work either. Here are logs:

```
2023-12-20 23:05:15.396 ERROR (MainThread) [custom_components.glinet4.router] GL-inet router http://192.168.8.1 responded with an unexpected error: 'online'
2023-12-20 23:05:15.396 WARNING (MainThread) [custom_components.glinet4.router] Router returned no valid connected devices. It returned None of type <class 'NoneType'>
2023-12-20 23:05:15.713 INFO (MainThread) [custom_components.glinet4.router] Reconnected to Gl-inet router http://192.168.8.1
2023-12-20 23:05:45.690 ERROR (MainThread) [custom_components.glinet4.router] GL-inet router http://192.168.8.1 responded with an unexpected error: 'online'
2023-12-20 23:05:45.691 WARNING (MainThread) [custom_components.glinet4.router] Router returned no valid connected devices. It returned None of type <class 'NoneType'>
2023-12-20 23:05:45.919 INFO (MainThread) [custom_components.glinet4.router] Reconnected to Gl-inet router http://192.168.8.1
2023-12-20 23:06:15.588 ERROR (MainThread) [custom_components.glinet4.router] GL-inet router http://192.168.8.1 responded with an unexpected error: 'online'
2023-12-20 23:06:15.588 WARNING (MainThread) [custom_components.glinet4.router] Router returned no valid connected devices. It returned None of type <class 'NoneType'>
2023-12-20 23:06:16.147 INFO (MainThread) [custom_components.glinet4.router] Reconnected to Gl-inet router http://192.168.8.1
2023-12-20 23:06:32.885 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139827655562944] Server disconnected
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/glinet4/switch.py", line 74, in async_turn_on
    await self._router.api.wireguard_client_stop()
  File "/usr/local/lib/python3.11/site-packages/gli4py/glinet.py", line 207, in wireguard_client_stop
    return await self._request(self.gen_sid_payload('call', ['wg-client', 'stop'], self.sid))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 32, in execute
    return await executable.execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 19, in invoke
    response = await callback.on_failure(type(error), error, tb)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 19, in invoke
    response = await callback.on_failure(type(error), error, tb)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 19, in invoke
    response = await callback.on_failure(type(error), error, tb)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/execution.py", line 108, in on_failure
    return self._io.fail(exc_type, exc_val, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/execution.py", line 128, in fail
    return self._io.fail(exc_type, exc_val, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/interfaces.py", line 300, in fail
    compat.reraise(exc_type, exc_val, exc_tb)
  File "/usr/local/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 16, in invoke
    response = await func(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/builder.py", line 47, in wrapper
    return func(self._consumer, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/hooks.py", line 110, in handle_exception
    compat.reraise(exc_type, exc_val, exc_tb)
  File "/usr/local/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 16, in invoke
    response = await func(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/builder.py", line 47, in wrapper
    return func(self._consumer, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/hooks.py", line 110, in handle_exception
    compat.reraise(exc_type, exc_val, exc_tb)
  File "/usr/local/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/io/asyncio_strategy.py", line 16, in invoke
    response = await func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uplink/clients/aiohttp_.py", line 133, in send
    response = await session.request(method, url, **extras)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 965, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by HarvsG** [comment]
Looks as if the API is reporting an unexpected response, either because the API has changed or I haven't encountered the response in my development/testing.

If you haven't already, can you provide your exact version number of the GL-inet router. http://192.168.8.1/#/upgrade
And the model of router.

**Comment by HarvsG** [comment]
> Current Firmware Version 4.4.6 Firmware Type release1

And which device?

**Comment by HarvsG** [comment]
Can you check you haven't fallen foul of this issue, which is the command in the readme was for the old version.
https://github.com/HarvsG/ha-glinet4-integration/issues/8

**Comment by leon0399** [comment]
Mine one: 
GL-MT3000 
Version: 4.4.6
Firmware Type: release2

I've confirmed, that my remote URL is for glinet4. latest `master` (01d60b45be77d81667a8281431c95641b9987959)

**Comment by HarvsG** [comment]
Can you enable debug logging  and post the output either side of the error (you'll have to click show full logs)
![Screenshot_20231230-133019](https://github.com/HarvsG/ha-glinet4-integration/assets/11440490/894665de-9fcf-4aff-852a-24fcd3179f3b)

**Comment by HarvsG** [comment]
Tested on multiple devices recently, try the latest version

**Comment by HarvsG** [comment]
@galaxyrun @leon0399  @mihsu81 
Any of you still having this issue? Otherwise I will close as stale.
